# -*- coding: utf-8 -*-
"""Bike_GUI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcCKY_dKnjBU2FKlvKLnT-p1BPpNaM2a
"""

!pip install -q gradio joblib

import gradio as gr
import joblib
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin


class BikeFeatureEngineer(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()

        X["datetime"] = pd.to_datetime(X["datetime"])

        X["year"] = X["datetime"].dt.year
        X["month"] = X["datetime"].dt.month
        X["day"] = X["datetime"].dt.day
        X["hour"] = X["datetime"].dt.hour
        X["dayofweek"] = X["datetime"].dt.dayofweek

        X["is_weekend"] = (X["dayofweek"] >= 5).astype(int)

        X["is_rush_hour"] = (
            X["hour"].isin([7, 8, 9, 16, 17, 18, 19])
        ).astype(int)

        X["is_peak_hour"] = (
            X["hour"].isin([8, 9, 17, 18])
        ).astype(int)

        X = X.drop(columns=["datetime"])

        return X

model = joblib.load("/content/bike_demand_model.pkl")



def predict_bike_demand(
    datetime, season, holiday, workingday, weather,
    temp, atemp, humidity, windspeed
):

    data = pd.DataFrame([{
        "datetime": datetime,
        "season": season,
        "holiday": holiday,
        "workingday": workingday,
        "weather": weather,
        "temp": temp,
        "atemp": atemp,
        "humidity": humidity,
        "windspeed": windspeed
    }])

    prediction = model.predict(data)[0]
    return round(max(0, prediction))


demo = gr.Interface(
    fn=predict_bike_demand,

    inputs=[
        gr.Textbox(
            label="Date & Time",
            value="2012-01-01 08:00:00"
        ),
        gr.Dropdown(choices=[1, 2, 3, 4],value=1,label="Season"),
        gr.Dropdown(choices=[0, 1],value=0,label="Holiday"),
        gr.Dropdown(choices=[0, 1],value=1,label="Working Day"),
        gr.Dropdown(choices=[1, 2, 3, 4],value=1,label="Weather"),
        gr.Number(value=9.84,label="Temperature"),
        gr.Number(value=14.395,label="Feels Like Temperature"),
        gr.Number(value=81,label="Humidity"),
        gr.Number(value=0,label="Windspeed")
      ],

    outputs=gr.Number(label="Predicted Bike Count"),
    title="Bike Sharing Demand Prediction",
    description="Enter the required information to predict bike rental demand."
)

demo.launch()